env:
  matrix:
    - NGINX_TAG='latest'
    - NGINX_TAG='dotdeb'
    - NGINX_TAG='backports'
build:
  pre_ci:
    - apt-get install -qqy ruby
    - gem install puppet --no-ri --no-rdoc
    - puppet module install puppetlabs/image_build
    - sed -ie 's/--show_diff//g' /etc/puppetlabs/code/modules/image_build/templates/Dockerfile.erb
    - puppet docker build --image-name luckyraul/nginx:$NGINX_TAG
  pre_ci_boot:
    image_name: luckyraul/nginx
    image_tag: $NGINX_TAG
    pull: false
  ci:
     - nginx -v
  push:
    - docker push luckyraul/nginx:$NGINX_TAG

integrations:
    hub:
      - integrationName: Docker
        type: docker
        agent_only: true
