env:
  matrix:
    - NGINX_TAG='latest'
    - NGINX_TAG='dotdeb'
    - NGINX_TAG='backports'
build:
  pre_ci:
    - apt-get install -qqy curl
    - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    - curl -L https://get.rvm.io | bash -s stable --ruby
    - source /usr/local/rvm/scripts/rvm
    - gem install puppet --no-ri --no-rdoc
    - puppet module install puppetlabs/image_build
    - puppet docker build --image-name luckyraul/nginx:$NGINX_TAG --no-show-diff
  pre_ci_boot:
    image_name: luckyraul/nginx
    image_tag: $NGINX_TAG
    pull: false
  ci:
     - nginx -v
  push:
    - docker push luckyraul/nginx:$NGINX_TAG

integrations:
    hub:
      - integrationName: Docker
        type: docker
        agent_only: true
