name: Docker MultiArch

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'bookworm'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Test Ruby Version
        run: ruby -v
      - id: install_puppet
        name: Install Puppet
        continue-on-error: true
        run: |
          sudo apt-get -qqy install git sudo ruby
          sudo gem install puppet --no-document
          sudo rm -fR /etc/puppetlabs/code/modules/image_build
          sudo git clone --single-branch --branch v2 https://github.com/luckyraul/puppetlabs-image_build.git /etc/puppetlabs/code/modules/image_build
      - name: Test Puppet Version
        run: puppet -V
      - name: Build Image
        run: |
          for arch in amd64 arm64 ; do
              sudo puppet docker build --image-name luckyraul/nginx:${{ matrix.version }}-$arch --no-show-diff --native --buildkit --platform linux/$arch --load --debug
          done
      - name: Test Image Version Amd64
        run: docker run --rm luckyraul/nginx:${{ matrix.version }}-amd64 nginx -v
      - name: Test Image Version Arm64
        run: docker run --rm luckyraul/nginx:${{ matrix.version }}-arm64 nginx -v
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Retag Images
        run: |
          docker tag luckyraul/nginx:${{ matrix.version }}-amd64 ghcr.io/luckyraul/nginx:${{ matrix.version }}-amd64
          docker tag luckyraul/nginx:${{ matrix.version }}-arm64 ghcr.io/luckyraul/nginx:${{ matrix.version }}-arm64
      - name: Push Images
        run: |
          docker push ghcr.io/luckyraul/nginx:${{ matrix.version }}-amd64
          docker push ghcr.io/luckyraul/nginx:${{ matrix.version }}-arm64
      - name: Create Manifest
        run: |
          docker manifest create ghcr.io/luckyraul/nginx:${{ matrix.version }} --amend ghcr.io/luckyraul/nginx:${{ matrix.version }}-arm64 --amend ghcr.io/luckyraul/nginx:${{ matrix.version }}-amd64
          docker manifest push ghcr.io/luckyraul/nginx:${{ matrix.version }}
      - name: Retag Images Mygento
        run: |
          docker tag ghcr.io/luckyraul/nginx:${{ matrix.version }}-amd64 ghcr.io/mygento/nginx:${{ matrix.version }}-amd64
          docker tag ghcr.io/luckyraul/nginx:${{ matrix.version }}-arm64 ghcr.io/mygento/nginx:${{ matrix.version }}-arm64
      - name: Push Images Mygento
        run: |
          docker push ghcr.io/mygento/nginx:${{ matrix.version }}-amd64
          docker push ghcr.io/mygento/nginx:${{ matrix.version }}-arm64
      - name: Create Manifest Mygento
        run: |
          docker manifest create ghcr.io/mygento/nginx:${{ matrix.version }} --amend ghcr.io/mygento/nginx:${{ matrix.version }}-arm64 --amend ghcr.io/mygento/nginx:${{ matrix.version }}-amd64
          docker manifest push ghcr.io/mygento/nginx:${{ matrix.version }}
